//!!!!!!!!!!!!!!!!
// To regenerate:
// 1) copy xsd.exe from C:\Program Files (x86)\Microsoft SDKs\Windows\{version}\bin\NETFX {version} Tools\
//   to c:\temp and place the xml there too
// 2) run xsd.exe authorities.xml
// 3) run: xsd.exe authorities.xsd /c /n:clientHasidicStories.Classes /nologo
// see : https://docs.microsoft.com/en-us/dotnet/standard/serialization/xml-schema-definition-tool-xsd-exe

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace clientHasidicStories.Classes
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.tei-c.org/ns/1.0", IsNullable = true)]
    public partial class idno
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.tei-c.org/ns/1.0", IsNullable = false)]
    public partial class TEI
    {
        public clsTEITeiHeader teiHeader { get; set; }
        public TEIText text { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class clsTEITeiHeader
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileDesc")]
        public TEITeiHeaderFileDesc fileDesc { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("profileDesc")]
        public TEITeiHeaderProfileDesc profileDesc { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDesc
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("titleStmt")]
        public TEITeiHeaderFileDescTitleStmt titleStmt { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publicationStmt")]
        public TEITeiHeaderFileDescPublicationStmt publicationStmt { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sourceDesc")]
        public TEITeiHeaderFileDescSourceDesc sourceDesc { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescTitleStmt
    {
        /// <remarks/>
        public string title { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescPublicationStmt
    {
        /// <remarks/>
        public string p { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescSourceDesc
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listPerson")]
        public TEITeiHeaderFileDescSourceDescListPerson[] listPerson { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("place", typeof(TEITeiHeaderFileDescSourceDescListPlace), IsNullable = false)]
        public TEITeiHeaderFileDescSourceDescListPlace[] listPlace { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescSourceDescListPerson
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("person")]
        public TEITeiHeaderFileDescSourceDescListPersonPerson[] person { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescSourceDescListPersonPerson
    {
        [System.Xml.Serialization.XmlAttributeAttribute("xml:id")]
        public string xmlid { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", IsNullable = true)]
        public TEITeiHeaderFileDescSourceDescListPersonPersonName[] name { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("birth", IsNullable = true)]
        public TEITeiHeaderFileDescSourceDescListPersonPersonBirth[] birth { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("death", IsNullable = true)]
        public TEITeiHeaderFileDescSourceDescListPersonPersonDeath[] death { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idno", IsNullable = true)]
        public idno[] idno { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescSourceDescListPersonPersonName
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescSourceDescListPersonPersonBirth
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string when { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescSourceDescListPersonPersonDeath
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string when { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescSourceDescListPlace
    {
        [System.Xml.Serialization.XmlAttributeAttribute("xml:id")]
        public string xmlid { get; set; }

        /// <remarks/>
        public string placeName { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("location")]
        public TEITeiHeaderFileDescSourceDescListPlacePlaceLocation location { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idno", IsNullable = true)]
        public idno[] idno { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderFileDescSourceDescListPlacePlaceLocation
    {
        /// <remarks/>
        public string geo { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITeiHeaderProfileDesc
    {
        /// <remarks/>
        public string textClass { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEIText
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("body")]
        public TEITextBody[] body { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tei-c.org/ns/1.0")]
    public partial class TEITextBody
    {
        /// <remarks/>
        public string p { get; set; }
    }
}